import { stringifyAsBsValue } from '../util/deterministic.js';

/**
 * Emit a single BrightScript file with a top-level `TemplateConfig()`
 * function returning the provided key-value pairs as an associative array.
 * Parallel to `emitModuleConfigBs` (per-module); this is template-level.
 *
 * Keys are sorted deterministically. Strings are escaped via the shared
 * `escapeBsString` helper in `src/util/deterministic.ts`, which throws
 * `APP_SPEC_INVALID` on control chars.
 */
export function emitTemplateConfigBs(config: Record<string, unknown>): string {
  const body = stringifyAsBsValue(config);
  return `' Auto-generated by brs-gen. Do not edit by hand.
function TemplateConfig() as object
  return ${body}
end function
`;
}
