import { stringifyAsBsValue } from '../util/deterministic.js';
import { moduleIdToBsId } from '../util/module-id.js';

export function emitModuleConfigBs(moduleId: string, config: Record<string, unknown>): string {
  const body = stringifyAsBsValue(config);
  // Dotted-namespace module ids (e.g. analytics.event_pipe) normalize to
  // BrightScript-safe identifiers via moduleIdToBsId.
  const bsId = moduleIdToBsId(moduleId);
  return `' Auto-generated by brs-gen. Do not edit by hand.
function ModuleConfig_${bsId}() as object
  return ${body}
end function
`;
}
