type Hook = { scope: string; phase: string; file: string; signature: string };

function dispatchFuncName(scope: string, phase: string): string {
  const parts = (scope + ' ' + phase).split(/[^A-Za-z0-9]+/).filter((p) => p.length > 0);
  const pascal = parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join('');
  return `Modules_On${pascal}`;
}

export function emitInitHooks(
  hooks: Hook[],
  initOrder: string[],
  callsByModule: ReadonlyMap<string, Array<{ hook: string; statement: string }>>,
  matchedOptional: ReadonlyArray<{ moduleId: string; hook: string; statement: string }> = [],
): string {
  const lines: string[] = ["' Auto-generated by brs-gen. Do not edit by hand.", ''];
  for (const h of hooks) {
    const name = dispatchFuncName(h.scope, h.phase);
    const hookKey = `${h.scope}.${h.phase}`;
    lines.push(`sub ${name}${h.signature}`);
    for (const modId of initOrder) {
      const calls = callsByModule.get(modId) ?? [];
      for (const c of calls) {
        if (c.hook === hookKey) {
          lines.push(`  ${c.statement}`);
        }
      }
    }
    for (const modId of initOrder) {
      for (const oc of matchedOptional) {
        if (oc.moduleId === modId && oc.hook === hookKey) {
          lines.push(`  ${oc.statement}`);
        }
      }
    }
    lines.push('end sub');
    lines.push('');
  }
  return lines.join('\n');
}
