import { stringifyAsBsValue } from '../util/deterministic.js';

export function emitModuleConfigBs(moduleId: string, config: Record<string, unknown>): string {
  const body = stringifyAsBsValue(config);
  // Dots in dotted-namespace module ids (e.g. analytics.event_pipe) are invalid in
  // BrightScript identifiers. Normalize to underscores for the generated function name.
  const bsId = moduleId.replaceAll('.', '_');
  return `' Auto-generated by brs-gen. Do not edit by hand.
function ModuleConfig_${bsId}() as object
  return ${body}
end function
`;
}
