import { stringifyAsBsValue } from '../util/deterministic.js';

export function emitModuleConfigBs(moduleId: string, config: Record<string, unknown>): string {
  const body = stringifyAsBsValue(config);
  return `' Auto-generated by brs-gen. Do not edit by hand.
function ModuleConfig_${moduleId}() as object
  return ${body}
end function
`;
}
